#!/usr/bin/env php
<?php

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require('/var/www/vendor/autoload.php');
require('/var/www/html/config/env.php');
require('/var/www/vendor/yiisoft/yii2/Yii.php');

// Build web configuration
$web = require('/var/www/html/config/web.php');
if (getenv_default('ENABLE_LOCALCONF', false) && file_exists('/var/www/html/config/local.php')) {
    $local = require('/var/www/html/config/local.php');
    $web = yii\helpers\ArrayHelper::merge($web, $local);
}

// Build console configuration
$config = require('/var/www/html/config/console.php');
if (getenv_default('ENABLE_LOCALCONF', false) && file_exists('/var/www/html/config/console-local.php')) {
    $local = require('/var/www/html/config/console-local.php');
    $config = yii\helpers\ArrayHelper::merge($config, $local);
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
