#!/usr/bin/env php
<?php

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__.'/config/env.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

// Build web configuration
$web = require(__DIR__.'/config/web.php');
if (getenv_default('ENABLE_LOCALCONF', false) && file_exists(__DIR__.'/../config/local.php')) {
    $local = require(__DIR__.'/config/local.php');
    $web = yii\helpers\ArrayHelper::merge($web, $local);
}

// Build console configuration
$config = require(__DIR__.'/config/console.php');
if (getenv_default('ENABLE_LOCALCONF', false) && file_exists(__DIR__.'/../config/console-local.php')) {
    $local = require(__DIR__.'/config/console-local.php');
    $config = yii\helpers\ArrayHelper::merge($config, $local);
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
