#!/usr/bin/env php
<?php

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require('/var/www/html/helpers/DockerEnv.php');
\DockerEnv::init();
$config = \DockerEnv::consoleConfig(['/var/www/html/tests/codeception/config/config.php']);

Yii::setAlias('@tests', '/var/www/html/tests');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
